Python/Console Applications/Web Projects/personal-site-blog/blog/urls.py
from . import views
from django.urls import path
from django.views.generic import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html'), name='home'),
    path('projects/', TemplateView.as_view(template_name='projects.html'), name='projects'),
    path('qualifications/', TemplateView.as_view(template_name='qualifications.html'), name='qualifications'),
    path('info/', TemplateView.as_view(template_name='info.html'), name='info'),
    path("blog/", views.PostList.as_view(), name="blog"),
    path("<slug:slug>/", views.post_detail, name="post_detail"),
]

Python/Console Applications/Web Projects/personal-site-blog/personalSite_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

Python/Console Applications/Web Projects/personal-site-blog/blog/models.py
from django.db import models
from django.contrib.auth.models import User


STATUS = (
    (0,"Draft"),
    (1,"Publish")
)


class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete= models.CASCADE,related_name='blog_posts')
    updated_on = models.DateTimeField(auto_now= True)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title

Python/Console Applications/Web Projects/personal-site-blog/blog/views.py
from django.views import generic
from .models import Post
from django.shortcuts import render, get_object_or_404


class PostList(generic.ListView):
    queryset = Post.objects.filter(status=1).order_by("-created_on")
    template_name = "blog.html"
    paginate_by = 3


# class PostDetail(generic.DetailView):
#     model = Post
#     template_name = 'post_detail.html'


def post_detail(request, slug):
    template_name = "post_detail.html"
    post = get_object_or_404(Post, slug=slug)

    return render(
        request,
        template_name,
        {
            "post": post
        },
    )

Python/Console Applications/Web Projects/personal-site-blog/templates/base.html
<!DOCTYPE html>
<html>

    <head>
        {% load static %}
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title class="page-title" idle="page-title">Christopher Fore</title>
        <link rel="stylesheet" href="{% static 'styles/styles.css' %}">
        <link rel="stylesheet" href="{% static 'styles/sidenav.css' %}">
        <link rel="shortcut icon" href="{% static 'images/sitelogo.png' %}">
        <script src="{% static 'scripts/script.js' %}" type = "text/javascript"/></script>
    </head>
    <body>
        <span style="font-size:30px;cursor:pointer" onclick="openNav()" class="hamburger"></span>
        <div id="mySidenav" class="sidenav">
            <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
            <a href="{% url 'home' %}">Home</a>
            <a href="{% url 'blog' %}">Blog</a>
            <a href="{% url 'projects' %}">Projects</a>
            <a href="{% url 'qualifications' %}">Qualifications</a>
            <a href="{% url 'info' %}">Info</a>
        </div>
        {% block content %}
        {% endblock content %}
    </body>
</html>

Python/Console Applications/Web Projects/personal-site-blog/templates/blog.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<p class="title">Blog</p>
<link rel="stylesheet" href="{% static 'styles/blogstyle.css' %}">
<div class="container">
  <div class="row">
    <!-- Blog Entries Column -->
    <div class="col-md-8 mt-3 left">
        <p class="intro">Welcome to the blog portion of my site, where I hope to write about neat things in the tech industry and anything else I hope people will find interesting. Comments are in the works for right now, but I hope to get them up and running soon!</p>
      {% for post in post_list %}
      <div class="card mb-4">
        <div class="card-body">
            <h2 class="card-title">{{ post.title }}</h2>
            <p class="card-text text-muted h6">Christopher Fore | {{ post.created_on}}  </p>
            <hr size="1" width="85%" color="black">
            <p class="card-text">{{post.content|safe|slice:":200" }}</p>
            <a href="{% url 'post_detail' post.slug  %}" class="btn btn-primary">Read More &rarr;</a>
        </div>

      </div>
      {% endfor %}

    </div>
  </div>
</div>
{% if is_paginated %}
    <nav aria-label="Page navigation conatiner"></nav>
    <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}
      <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
      {% endif %}
      {% if page_obj.has_next %}
      <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>

{% endif %}
</ul>
</nav>
</div>
{% endif %}
{%endblock%}

Python/Console Applications/Web Projects/personal-site-blog/templates/index.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<!-- Use any element to open the sidenav -->
<p class="title">Home</p>
<div class="images" id="images">
    <img src="{% static 'images/tux.png' %}">
</div>

<div id="main" class="main">
    <p>
        Hi! This is my personal site. I'm Christopher Fore, a graduate of Highland School of Technology, and an
        entering underclassman at Rochester Institute of Technology (RIT) in Fall 2022. I have a passion for computers
        and programming, with knowledge in: Python, C++, HTML/CSS, Flutter, Kotlin, and JavaScript. I am not
        an expert by any means in any of these languages, but I am more proficient in Python and C++. At RIT,
        I hope to major in Computing Security, with hopes of entering the Information Security Analyst field,
        but I also have interests in the System Administrator and Network Engineer fields.
    </p>
    <div class="skills">
        <table>
            <tr>
                <th>Ability</th>
                <th>Skill Level</th>
            </tr>
            <tr>
                <td>C++</td>
                <td>Mid-Beginner</td>
            </tr>
            <tr>
                <td>Python</td>
                <td>Upper-Beginner</td>
            </tr>
            <tr>
                <td>JavaScript</td>
                <td>Early Beginner</td>
            </tr>
            <tr>
                <td>Bash</td>
                <td>Early Beginner</td>
            </tr>
            <tr>
                <td>HTML/CSS</td>
                <td>Intermediate</td>
            </tr>
            <tr>
                <td>Git</td>
                <td>Mid-Beginner</td>
            </tr>
            <tr>
                <td>Flutter</td>
                <td>Mid-Beginner</td>
            </tr>
        </table>
    </div>
</div>
{%endblock%}

Python/Console Applications/Web Projects/personal-site-blog/templates/info.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<p class="title">Info</p>
<div class="container">

</div>

{% endblock content %}

Python/Console Applications/Web Projects/personal-site-blog/templates/post_detail.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'styles/postdetailstyle.css' %}">
<div class="container">
  <div class="row">
    <div class="col-md-8 card mb-4  mt-3 left  top">
      <div class="card-body">
        <p class="card-title">{{ post.title }}</p>
        <p class=" text-muted">Christopher Fore | {{ post.created_on }}</p>
        <hr size="2" width="85%" color="black">
        <p class="card-text ">{{ post.content | safe }}</p>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

Python/Console Applications/Web Projects/personal-site-blog/templates/projects.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<!-- Use any element to open the sidenav -->
<p class="title">Projects</p>
<div id="main" class="main">
    <p>
        Here are my projects! You'll find a list of them below.
    </p>
</div>
{% endblock content %}

Python/Console Applications/Web Projects/personal-site-blog/templates/qualifications.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<!-- Use any element to open the sidenav -->
<p class="title">Qualifications</p>
<div id="main" class="main">
    <p>
        Currently, I am a certified Microsoft Office Specialist Master and Microsoft Technology Associate in Introduction
        to Programming using Python. The following certificates are as shown below.
    </p>
    <img src="{% static 'images/MOSMaster.png' %}" width="550" height="425" style="margin-left: 10%; padding-top: 1.5%">
    <img src="{% static 'images/pythonCert.png' %}" width="550" height="425" style="margin-left: 10%; padding-top: 1.5%">
    <p>
        I also have 3 years of experience in computer repair, including repairing some personal computers I've acquired
        over the years. I have about 6 months of experience in Python, but I've learned a lot since I began. I have about
        7 months of experience in C++, but I haven't practiced C++ as much as I have regarding Python.
    </p>
</div>
{% endblock content %}

Python/Console Applications/Web Projects/personal-site-blog/templates/sidebar.html
{% block sidebar %}



<!-- Sidebar Widgets Column -->
<div class="col-md-4 float-right ">
    <div class="card my-4">
        <h5 class="card-header">About Us</h5>
        <div class="card-body">
            <p class="card-text"> This awesome blog is made on the top of our Favourite full stack Framework 'Django',
                follow up the tutorial to learn how we made it..!</p>
            <a href="#" class="btn btn-danger">Know more!</a>
        </div>
    </div>
</div>

{% endblock sidebar %}